name: chalet_spot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  badges: ^3.1.2
  bloc: ^8.1.4
  cached_network_image: ^3.4.0
  calendar_date_picker2: ^1.1.5
  carousel_slider: ^5.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.5.0+1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon_app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon_app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon_app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/icons/
    - assets/icons/admin/
    - assets/icons/media/
    - assets/icons/amenities/
    - assets/icons/bottom_icons/
    - assets/translations/
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
