// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLsxaQq68GRq-F_eUHBDTh-tnXWvJuZo',
    appId: '1:594283498220:web:0ae00e56308e03fd9bf3c9',
    messagingSenderId: '594283498220',
    projectId: 'chalet-spot',
    authDomain: 'chalet-spot.firebaseapp.com',
    storageBucket: 'chalet-spot.appspot.com',
    measurementId: 'G-BZBZBPF7N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdue4F5-DUxnhAkvjhyATp23AvORs6rZk',
    appId: '1:594283498220:android:7f78fe15dfb24d449bf3c9',
    messagingSenderId: '594283498220',
    projectId: 'chalet-spot',
    storageBucket: 'chalet-spot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGX6eiGIzR_aAOwF-Lp4DDZJqbTADc5Y0',
    appId: '1:594283498220:ios:d7c31ba4c454ead79bf3c9',
    messagingSenderId: '594283498220',
    projectId: 'chalet-spot',
    storageBucket: 'chalet-spot.appspot.com',
    iosBundleId: 'com.example.chaletSpot',
  );
}
